recipes-trustx/userdata/userdata.bb
copy guest OS to data image in order to be able to start cmld after following quick start at
https://github.com/trustm3/trustme_build/blob/master/yocto/README.md
=> extend package userdata of recipe trustx-cml-userdata:

recipes-trustx/service/service_git.bb
This patch properly installs init script for cml_service_container
somewhere in /etc directory of the container. Thus, the BOOT_COMPLETE
will be send automatically to cmld.
=> service_git.bb: Fixed init script installation

images/trustx-cml-initramfs.bb
Assure writable /tmp directory on read-only rootfs
=> Assure /tmp is writable when rootfs is read-only

images/trustx-cml-initramfs.bb, recipes-initscripts/cml-boot/files/cml-boot-script.stub, recipes-poky/base-files/base-files/fstab, recipes-poky/base-files/base-files_%.bbappend, recipes-poky/busybox/busybox-inittab/inittab, recipes-poky/busybox/busybox-inittab_%.bbappend
This commit fixes race condition between busybox init
and cmld mounting toofs read-only. Further, CML-specific labeled
partitions are now properly defined in fstab and are mounted by
init script with mount -a. This makes the sleeps in init script
obsolete.
=> Proper fstab and init script for cml

recipes-initscripts/cml-boot/files/cml-boot-script.stub, recipes-poky/base-files/base-files/fstab
This patch starts udevd after /run is mounted, thus preventing
sockets created on wrong file system. Further, udevd is not
destroyed anymore since it is needed for udev events in cmld
uevent subsystem now. The fstab was fixed accordingly with
more restrictive mount options.
=> cml-boot: Fixed udevd start and proper fstab

classes/trustmegeneric.bbclass, images/trustx-cml-firmware.bb, recipes-kernel/linux/linux-%.bbappend, recipes-poky/base-files/base-files/fstab
To ease kernel updates, this patch introduces a new image for
firmware files and modifies the kernel recipes to produce a squashfs
image with all modules. The fstab and trustmegeneric.bbclass is
adopted to use the new images instead of just directories in /data.
=> Provide modules and firmware as loop mounted squashfs images

classes/trustmegeneric.bbclass
Together with patches in device_fraunhofer_common_cml an trustme_build this patch enables the system to boot even if no c0 was built and thus enables the user to provide c0 manually.
=> fix check for non-existant c0

classes/trustmegeneric.bbclass
If there are some out-of-tree modules present, unsquash the
kernel modules image to a temporary location. Copy the out-of-tree
modules there and overwrite old squashfs image with new
mksquashfs of the temporary directory.
=> classes/trustmegeneric: include out-of-tree modules in image

images/trustx-cml-initramfs.bb, recipes-sc-hsm-cardservice/sc-hsm-cardservice/sc-hsm-cardservice_git.bb, recipes-trustx/cmld/cmld_git.bb
This PR allows to integrate sc-hsm by CardContact [1] into trust|me to make use of usb token.
The SRC_URI in the Bitbake recipe actually points to a fork in the trustm3 space [2].
[1] https://github.com/CardContact/sc-hsm-embedded
[2] https://github.com/trustm3/sc-hsm-embedded
=> Add sources to build sc-hsm support

recipes-kernel/linux/linux-vanilla/4.19/0001-shiftfs-uid-gid-shifting-bind-mount.patch, recipes-kernel/linux/linux-vanilla/4.19/0002-shiftfs-rework-and-extend.patch, recipes-kernel/linux/linux-vanilla/4.19/0003-shiftfs-support-some-btrfs-ioctls.patch, recipes-kernel/linux/linux-vanilla/4.19/0004-UBUNTU-SAUCE-shiftfs-use-translated-ids-when-chaning.patch, recipes-kernel/linux/linux-vanilla/4.19/0005-UBUNTU-SAUCE-shiftfs-fix-passing-of-attrs-to-underal.patch, recipes-kernel/linux/linux-vanilla/4.19/0006-UBUNTU-SAUCE-shiftfs-prevent-use-after-free-when-ver.patch, recipes-kernel/linux/linux-vanilla/4.19/0007-UBUNTU-SAUCE-shiftfs-use-separate-llseek-method-for-.patch, recipes-kernel/linux/linux-vanilla/4.19/0008-UBUNTU-SAUCE-shiftfs-lock-down-certain-superblock-fl.patch, recipes-kernel/linux/linux-vanilla/4.19/0009-UBUNTU-SAUCE-shiftfs-allow-changing-ro-rw-for-subvol.patch, recipes-kernel/linux/linux-vanilla/4.19/0010-UBUNTU-SAUCE-shiftfs-enable-overlayfs-on-shiftfs.patch, recipes-kernel/linux/linux-vanilla/4.19/0011-UBUNTU-SAUCE-shiftfs-add-O_DIRECT-support.patch, recipes-kernel/linux/linux-vanilla/4.19/0012-UBUNTU-SAUCE-shiftfs-pass-correct-point-down.patch, recipes-kernel/linux/linux-vanilla/4.19/0013-UBUNTU-SAUCE-Revert-UBUNTU-SAUCE-shiftfs-enable-over.patch, recipes-kernel/linux/linux-vanilla/4.19/0014-UBUNTU-SAUCE-shiftfs-mark-slab-objects-SLAB_RECLAIM_.patch, recipes-kernel/linux/linux-vanilla/4.19/0015-UBUNTU-SAUCE-shiftfs-fix-buggy-unlink-logic.patch, recipes-kernel/linux/linux-vanilla/4.19/0016-UBUNTU-SAUCE-shiftfs-Fix-refcount-underflow-in-btrfs.patch, recipes-kernel/linux/linux-vanilla/4.19/0017-UBUNTU-SAUCE-shiftfs-prevent-type-confusion.patch, recipes-kernel/linux/linux-vanilla/4.19/0018-UBUNTU-SAUCE-shiftfs-Correct-id-translation-for-lowe.patch, recipes-kernel/linux/linux-vanilla/4.19/0019-UBUNTU-SAUCE-shiftfs-Restore-vm_file-value-when-lowe.patch, recipes-kernel/linux/linux-vanilla/4.19/0020-UBUNTU-SAUCE-shiftfs-setup-correct-s_maxbytes-limit.patch, recipes-kernel/linux/linux-vanilla/4.19/0021-UBUNTU-SAUCE-shiftfs-drop-CAP_SYS_RESOURCE-from-effe.patch, recipes-kernel/linux/linux-vanilla/4.19/0022-UBUNTU-SAUCE-shiftfs-prevent-lower-dentries-from-goi.patch, recipes-kernel/linux/linux-vanilla/4.19/0023-shiftfs-backport-to-v4.19.patch, recipes-kernel/linux/linux-vanilla_4.19.%.bbappend
This patch updates shiftfs for 4.19. It replaces the patchset extracted
from the kernel mailing list by a ported patchset from ubuntu's disco
(v5.0) kernel:
https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/disco/
for i in `git log --pretty=oneline disco/master -- fs/shiftfs.c| \
awk '{print $1}'`; do echo $i >> commits-reverse; done
for i in `tac commits-reverse`; do git cherry-pick $i; done
=> recipes-kernel/linux/linux-vanilla: updated 4.19 with proper shiftfs

recipes-initscripts/cml-boot/files/cml-boot-script.stub
Moved otf progress bar from logtty (tty11) to /dev/console.
Further, the output of dd was sanitized.
=> cml-boot/files/cml-boot-script: show progress of otf on /dev/console

recipes-sc-hsm-cardservice/sc-hsm-cardservice/sc-hsm-cardservice_git.bb
Update the SRC_URI of the sc-hsm-cardservice recipe to use https instead of ssh. Also exclude the key-generator example to minimize the codebase.
=> Update SRC_URI of sc-hsm-cardservice recipe

recipes-sc-hsm-cardservice/sc-hsm-cardservice/sc-hsm-cardservice_git.bb
This ensures that the sc-hsm-cardservice is always built from the newest commit
in [1].
[1]https://github.com/trustm3/sc-hsm-embedded
Signed-off-by: Christian Epple <christian.epple@aisec.fraunhofer.de>
=> sc-hsm-cardservice: update SRCREV

recipes-initscripts/cml-boot/files/cml-boot-script.stub
Also copy signature and certificate files of c0 container config
template folder if available to /data/cml/containers.
=> cml-boot/files/cml-boot-script.stub: c0 template sig and cert

recipes-initscripts/cml-boot/files/cml-boot-script.stub
Fix a syntax error in the cml init script that prevented the image from booting
=> Fix syntax in cml init script

images/trustx-cml-initramfs.bb, recipes-sc-hsm-cardservice/sc-hsm-cardservice/files/0001-build-a-cardservice-library.patch, recipes-sc-hsm-cardservice/sc-hsm-cardservice/files/0002-Fix-includes-for-MUSL-builds.patch, recipes-sc-hsm-cardservice/sc-hsm-cardservice/sc-hsm-embedded_2.11.bb, recipes-trustx/cmld/cmld_git.bb
Use upstream sc-hsm-embedded sources and patch them as needed
instead of using a dedicated fork.
=> sc-hsm-embedded: switch to versioned built from upstream

recipes-initscripts/cml-boot/files/cml-boot-script.stub, recipes-poky/base-files/base-files/fstab
Allow usage of externally provided 9p btrfs to be mounted
as overlay over /mnt/userdata to /data. This enables the user
i.a. to work with larger guestsOSes in a virtualized environment.
=> Enable usage of external btrfs as /data

recipes-initscripts/cml-boot/files/cml-boot-script.stub
Wait untill '/dev/disk/by-label/boot' will appear in file system.
This should fix a race which may lead to an wrong device name for
for file system encryption of the trustme partition.
=> cml-boot/files/cml-boot-script.stub: wait for boot partition

recipes-initscripts/cml-boot/files/cml-boot-script.stub
On some platforms, the partition labels are not properly recognized
prior to tpm2d initialization.
Therefore, this commit runs blkid to assure the partition labels are scanned.
=> cml-boot: Run blkid before attempt to access partitions

recipes-initscripts/cml-boot/files/cml-boot-script.stub
This commit fixes a bug that leads to an erroneous mount of
an overlayfs on /data.
The mount command must not be invoked with the "nofail" option in
the cml-boot script.
Signed-off-by: Christian Epple <christian.epple@aisec.fraunhofer.de>
=> cml-boot: Fix extdata mount

recipes-initscripts/cml-boot/files/cml-boot-script.stub
The start of the tpm2d hinders remounting the rootfs readonly.
Therefore, start the tpm2d after the cmld.
Signed-off-by: Simon Ott <simon.ott@aisec.fraunhofer.de>
=> cml-boot: Fix boot order

images/trustx-core.bb, recipes-poky/pam/libpam_%.bbappend
added bbappend to enable audit in libpam and added shadow to trustx-core
packes list. Further replaced dropbear by openssh server to also get the
pam_loginuid module in place.
=> images/trustx-core: enable pam for audit

recipes-trustx/service/service-static_git.bb
Also build and install exec_cap_systime which may be injected
during runtime into containers for testing the ability to execute
processes with host CAP_SYS_TIME in containers.
=> recipes-trustx/service/service-static: build exec_cap_systime

recipes-initscripts/cml-boot/files/cml-boot-script.stub
The SCD is now started by the CMLD
Signed-off-by: Simon Ott <simon.ott@aisec.fraunhofer.de>
=> cml-boot: Do not start SCD

images/trustx-signing.inc
=> images/trustx-signing.inc: add missing python-protobuf dependency

images/trustx-signing.inc
=> images/trustx-signing.inc: add missing python3-protobuf dependency

images/trustx-signing.inc
This should finally fix builds in docker environment provided
by trustme/build repository.
=> images/trustx-signing.inc: add missing python3 dependency

recipes-trustx/trusted-connector/trusted-connector_git.bb
The upstream branch currently used in trusted_connector_git.bb was deleted.
As this causes all builds to fail, this commit changes the branch to the master branch.
It has to be tested, if this branch still works for the images depending on it.
=> trusted_connector: Upstream branch was deleted

images/trustx-cml-initramfs.bb
mknod for /dev/console is made by cml-boot recipe now. Thus, remove
it here from update_inittab image post processing command to avoid
EEXIST.
=> images/trustx-cml-initramfs: fixed update_inittab in dev build

images/trustx-core.bb
Apply the current version of guestos to 00..0.conf template. This
is necessary if signed configs are enabled in device.conf. Because in
that case, the guestos version may not be updated without resigning.
=> images/trustx-core: applied guestos version to 00..0.conf template

recipes-trustx/cmld/cmld_git.bb
This commit adds support for the CC_MODE flag to cmld_git.bb
=> cmld_git: Add support for CC_MODE

recipes-trustx/cmld/cmld_git.bb, recipes-trustx/service/service-static_git.bb, recipes-trustx/service/service_git.bb
Switched the trustx recipes for cmld and service from zeus to dunfell.
=> recipes-trustx/{cmld|service}: switched to dunfell branch

images/trustx-signing.inc
This commit adapts the trustx-signing.inc script
to the new structure of the test PKI.
Now, the certificate ssig_cml.cert is used to sign GuestOS
and container configuration files.
=> trustx-signing.inc: Use certificate with RSA-PSS padding scheme

recipes-kernel/linux/linux-vanilla/0001-dm-integrity-Generate-audit-events-for-integrity-vio.patch, recipes-kernel/linux/linux-vanilla/5.4/0001-dm-report-suspended-device-during-destroy.patch, recipes-kernel/linux/linux-vanilla_5.10.%.bbappend, recipes-kernel/linux/linux-vanilla_5.4.%.bbappend
Use the wip patch for dm-integrity to generate audit events in
case of integrity violations (io errors).
=> recipes-kernel/linux: added patch for dm-integrity audit events

recipes-selinux/selinux/fixedpatch/0001-Fix-NULL-pointer-use-in-selinux_restorecon_set_sehandle.patch, recipes-selinux/selinux/libselinux_%.bbappend
Commit d6ff5a0e67afe519ce3c03a92d423481e4e41ca2
introduced a backported patch with an erroneus prefix
into the dunfell branch of meta-selinux.
This commit overrides the prefix to re-enable the
trustme build until the issue is fixed upstream.
=> recipes-selinux: Temporary fix for bug in meta-selinux

recipes-initscripts/cml-boot/files/cml-boot-script.stub
Introduce scan_devices function. We use scan_devices until boot disk
comes available.
=> recipes-initscripts/cml-boot: add scan_devices to init script

classes/trustmegeneric.bbclass
Fixed error when signing the container config, which has to be done with the ssig_cml.key, not the old ssig.key.
=> classes: Fixed signing error in trustmegeneric.bbclass

classes/trustmegeneric.bbclass
Copying update files must be done in do_build_trustmeimage where the
image is assembled. Can't be in trustx-cml.bbappend.
=> Install kernel update files into trustmeimage

classes/trustmegeneric.bbclass
Copying update files must be done in do_build_trustmeimage where the
image is assembled. Can't be in trustx-cml.bbappend.
(cherry picked from commit 2ef02bfb5a1bec58bf866e637d7eb4cf8d5f8ff0)
=> Port kernel update signing back to v0.9

recipes-kernel/linux/linux-vanilla/5.4/0043-batman-adv-user-ns-netlink.patch, recipes-kernel/linux/linux-vanilla_5.4.%.bbappend
Add patch to change GENL_ADMIN_PERM to GENL_UNS_ADMIN_PERM to enable the usage of netlink messages with the batman-adv kernel module in unprivileged containers.
Apply patch to kernel version 5.4
From Kernel version 5.4.174 and onward this patch won't be necessary any longer as it was included into mainline.
Signed-off-by: Markus Eckert <meckert@blackned.de>
=> Patch batman-adv: Allow netlink usage in container

recipes-kernel/linux/linux-vanilla/5.4/0001-dm-introduce-audit-event-module-for-device-mapper.patch, recipes-kernel/linux/linux-vanilla/5.4/0002-dm-integrity-log-audit-events-for-dm-integrity-targe.patch, recipes-kernel/linux/linux-vanilla/5.4/0003-dm-crypt-log-aead-integrity-violations-to-audit-subs.patch
The backport of the mainline dm-audit patches was wrong. Because of a misuse of MAJOR() on a variable which already contains the major, the major of the device in the audit event message was '0'. This is fixed now.
=> recipes-kernel/linux/linux-vanilla/5.4: fixed dm-audit backport

recipes-sc-hsm-cardservice/sc-hsm-cardservice/sc-hsm-embedded_2.11.bb, recipes-trustx/cwrap/uid-wrapper_1.2.8.bb
Correctly sets PV using SRCPV and therefore fixing: ERROR: uid-wrapper-1.2.8-r0 do_fetch: Bitbake Fetcher Error:
FetchError("Recipe uses a floating tag/branch without a
fixed SRCREV yet doesn't call bb.fetch2.get_srcrev()
(use SRCPV in PV for OE).", None)
Signed-off-by: Johannes Wiesboeck <johannes.wiesboeck@aisec.fraunhofer.de>
=> Fix revision error in tagged git URIs

recipes-kernel/linux/linux-vanilla/5.4/0001-dm-introduce-audit-event-module-for-device-mapper.patch, recipes-kernel/linux/linux-vanilla/5.4/0002-dm-integrity-log-audit-events-for-dm-integrity-targe.patch, recipes-kernel/linux/linux-vanilla/5.4/0003-dm-crypt-log-aead-integrity-violations-to-audit-subs.patch
The backport of the mainline dm-audit patches was wrong. Because of a misuse of MAJOR() on a variable which already contains the major, the major of the device in the audit event message was '0'. This is fixed now.
(cherry picked from commit 5aca57b8c0feb93838f8b2f8a228d55ed3e0a076)
=> V0.9 recipes-kernel/linux/linux-vanilla/5.4: fixed dm-audit backport

recipes-tss/tss2/ibmtss2_1331.bb
On kirkstone compilation currently fails due to multiple definitions for the same symbol in two different files. These files are Commands.c and Commands12.c corresponding to TPM2.0 and TPM1.2 implementations respectively.
A simple fix is to disable TPM1.2 support for this version of ibmtss2. I would recommend bumping ibmtss2 to version 1.6.0 later in the kirkstone migration process which should fix this problem itself and then drop this version of ibmtss2. For now this is the lowest impact fix to get compilation going again.
Feel free to suggest better fixes, i'm out of ideas.
Attached Error Messages:
/opt/ws-yocto/out-x86-production/tmp/work/core2-64-poky-linux-musl/ibmtss2/1331-r0/recipe-sysroot-native/usr/bin/x86_64-poky-linux-musl/../../libexec/x86_64-poky-linux-musl/gcc/x86_64-poky-li …
=> recipes-tss/tss2/ibmtss2: Drop support for TPM1.2

images/trustx-signing.inc, recipes-trustx/cmld/cml-common.inc, recipes-trustx/cmld/cmld_git.bb, recipes-trustx/service/service-static_git.bb, recipes-trustx/service/service_git.bb
This PR makes a set of changes to support building the cml related recipes from the local checkout, while maintaining the ability to build from git if the checkout is missing.
The changes are:
1. Refactor the cml related recipes (cmld, service, service-static) to obtain their source information from one common include (cml-common.inc).
2. Fix errors due to missing '/' in paths.
3. Conditionally set EXTERNALSRC(_BUILD) in cml-common.inc depending on the existence of the cml repo checkout.
4. Install cml protobuf files to the sysroot to be obtained by trustx-signing. This is required if cmld is build from git and no checkout is available, thus breaking the old path to the protobuf file.
=> Build cml using externalsrc

recipes-trustx/cmld/cml-common.inc, recipes-trustx/cmld/cmld_git.bb, recipes-trustx/service/service-static_git.bb, recipes-trustx/service/service_git.bb
We require cmld and service* to be built using dfferent variants of libc for container and host builds (e.g. glibc and musl). Build in-source poisons the source directory with artifacts compiled with another libc and thus breaks the build if building glibc containers. Thus, we need to keep the source directory clean and copy the sources to the build directory first.
=> recipes-trustx/*: Build cml-related recipes out-of-tree

recipes-kernel/linux/linux-rolling-stable_git.bb
This commit adapts the linux-rolling-stable recipe to use the kirkstone syntax for prepending.
=> linux-rolling-stable: Change to new syntax

recipes-poky/busybox/busybox-inittab_%.bbappend
Automatically spawned gettys can intefere with some GyroidOS builds. Therefore, this commit  sets
SYSVINIT_ENABLED_GETTYS="" to remove gettys enabled by Yocto / Poky.
=> recipes-poky/busybox: Disable automatic gettys

conf/templates/default/local.conf.sample
With the current config, mkfs.btrfs is not installed on kirkstone. Install it by enabling "programs" for btrfs-tools.
=> local.conf: Install btrfs programs

recipes-kernel/linux/linux-gyroidos.inc
Currently upstream is being worked on the bug: bugzilla 15059 [https://bugzilla.yoctoproject.org/show_bug.cgi?id=15059] For kirkstone there is no fix yet and only a partial fix is in master: "kernel: improve initramfs bundle processing time" [01f0a371b139d35a6f6f39fdd96f0d1a796684d7]
Our workaround activates the parallel make in KERNEL_EXTRA_ARGS having the same effect as the upstream partial fix:
=> recipes-kernel/linux/linux-gyroidos: speed up do_bundle_initramfs

recipes-poky/base-files/base-files/fstab
Instead of btrfs make use of ext4 container storage image. This should help to make Jenkins tests more stable against killed qemu instances.
=> recipes-poky/base-files: use ext4fs for containers in fstab

classes/trustmegeneric.bbclass, images/trustx-core.bb, images/trustx-signing.inc
This PR changes the deploy behavior of guestos images and trustx-cml to deploy their artifacts via the IMGDEPLOYDIR directory. This automatically reenables deploying the cml-updates directory which is created in the trustx-cml recipe when using meta-trustx-intel.
=> Deploy images via IMGDEPLOYDIR

conf/multiconfig/container_qemuarm.inc, conf/multiconfig/container_qemuarm64.inc
Since on some arm build variants, e.g., raspberrypi, the variable KERNEL_DEVICETREE needs to be present, otherwise parsing errors may occur. Thus, we clear that variable. The container multiconfig uses a dummy kernel and no device tree should be added to the container image anyway.
=> conf/multiconfig/container_qemuarm*: set empty KERNEL_DEVICETREE

recipes-poky/pv/pv/0001-pv-display-handle-error-of-tcgetpgrp-in-pv_in_foregr.patch, recipes-poky/pv/pv_%.bbappend
Current pv version does not display any output if invoked without a tty terminal present for current process. This is also the case if invoked by busybox init script. The patch solves this. see "pv Stopped Working in the Background #55"
(https://github.com/a-j-wood/pv/issues/55)
=> recipes-poky/pv: added bbappend with patch for foreground operation

recipes-kernel/linux/linux-rolling-stable_git.bb
Fixed the syntax for declaring the machine specific variable which selects the kernel default config.
=> recipes-kernel/linux/linux-rolling-stable: variable syntax fixed

images/trustx-cml-firmware.bb
When not building from scratch but after the image has already been built once these rmdirs fail because of non-existent directories. This is fixed by also using rm -rf as this ignores non-existent directories silently.
=> images/trustx-cml-firmware: Replace rmdir with rm -rf

recipes-kernel/linux/linux-rolling-stable_git.bb, recipes-kernel/linux/linux-vanilla_%.bbappend
Set PV from git to 1.0, to allow generated package also be installed on debian. Set homepage to kernel.org. Set LINUX_VERSION_EXTENSION to "-gyroidos".
=> recipes-kernel/linux/linux-rolling-stable: sanitize packaging

recipes-trustx/service/service-static_git.bb
For static builds 'cml-service-container' has been renamed to 'cml-service-container-static'.
s. https://github.com/gyroidos/cml/pull/414
=> recipes-trustx/service/service-static_git.bb: Update binary name

recipes-kernel/linux/linux-rolling-stable_git.bb
Allow to set LINUX_VERSION as part of PV. Use version "1.0" as fallback if no LINUX_VERSION is provided by local.conf or auto.conf.
=> recipes-kernel/linux/linux-rolling-stable: allow to set LINUX_VERSION

classes/trustmegeneric.bbclass
This PR fixes size calculation of additional free space that is specified through TRUSTME_DATAPART_EXTRA_SPACE.
=> classes/trustmegeneric.bbclass: Fix extra space

images/trustx-cml.bb
This commit disables signature enforcement in development builds. This is needed due to the changed default in PR gyroidos/cml#415.
=> trustx-cml-initramfs: Signed configs in dev builds

images/trustx-cml-initramfs.bb, images/trustx-cml.bb
Retrieving the kernel version requires the file
${STAGING_KERNEL_BUILDDIR}/kernel-abiversion to be exist. When the
kernel is checked out from sstate-cache this file is not created.
Forcing the kernel workdir to be deployed fixes this problem.
NB: Other recipes implement this mechanism by inheriting the kernelsrc
class which is similar but puts the dependency on the do_patch task,
that is not available in an image build. Therefore, we implement this by
hand, by manually depending on the do_shared_workdir from the do_rootfs
task.
=> images/trustx-cml-initramfs: Deploy kernel before build

recipes-initscripts/cml-boot/cml-boot_1.0.bb, recipes-initscripts/cml-boot/files/start_sshd
This file contains the commands to start the openSSH server in the cml layer. If the feature is activated (in dev builds) its contents are copied into the init script.
In previous commits regarding the openSSH integration into the cml layer this file was accidentally not commited resulting in the SSH server not starting at boot. This is hereby fixed.
=> recipes-initscripts/cml-boot: Add missing file for SSH server start

recipes-kernel/linux/linux-vanilla/0001-ipvs-allow-netlink-configuration-from-non-initial-us.patch, recipes-kernel/linux/linux-vanilla_%.bbappend
Added 0001-ipvs-allow-netlink-configuration-from-non-initial-us.patch which allows to run VRRP services inside a user namespaced GyroidOS container, e.g., ipvsadm.
=> recipes-kernel/linux/linux-vanilla: allow netlink for ipvs in userns

conf/templates/default/local.conf.sample
btrfs-progs-native
Recent builds break because btrfs-tools-native enable python features by default without defining the dependency in yocto. Like for the target version, disable the python features for the native build.
=> conf/templates/default/local.conf.sample: PACKAGECONFIG for

images/trustx-cml/device.conf
With the new feature of container relative update urls, we should default to the relative path, as this will work more robustly across different setups. Therefore remove the leading tmp/<container_uid> directory.
=> images/trustx-cml/device.conf: make default update_base_url relative.

classes/trustmegeneric.bbclass
Allow TRUSTME_DATAPART_EXTRA_SPACE to be set in local.conf, to avoid running out of disk space during integration tests
=> classes/trustmegeneric: Allow to overwrite TRUSTME_DATAPART_EXTRA_SPACE

images/trustx-cml/device.conf
Added audit_size parameter to enable audit logging by default. Thus, it will be tested if there are any regressions during pull request testing in our Jenkins  pipeline.
=> images/trustx-cml/device.conf: enable audit logging

recipes-kernel/linux/generic/0001-tools-lib-subcmd-Fixed-uninitialized-use-of-variable.patch, recipes-kernel/linux/linux-gyroidos.inc
Our asan build sets "-Og" for all packages, including the kernel. Add patch which was submitted upstream to fix uninitialized use of variable in 'tools/lib/subcmd'.
=> recipes-kernel/linux/linux-gyroidos: added patch for asan builds

recipes-initscripts/cml-boot/cml-boot_1.0.bb, recipes-initscripts/cml-boot/files/cml-boot-script.stub
This PR adapts the core dump pattern s.t. in production builds root namspace PIDs of containerized processes are not included in the core dump name.
=> recipes-initscripts/cml-boot: Adapt core pattern

recipes-kernel/linux/linux-vanilla/0001-kbuild-remove-recent-dependency-on-truncate-program.patch, recipes-kernel/linux/linux-vanilla_%.bbappend
Added 0001-kbuild-remove-recent-dependency-on-truncate-program.patch which allows to build the current rolling stable kernel in yocto. This patch is already in the kbuild tree for-next. Thus we need to remove this again when rolling stable hits this.
=> recipes-kernel/linux/linux-vanilla: remove kbuild truncate dependency

recipes-initscripts/cml-boot/files/cml-boot-script.stub
tmp2d looks to open log files in `/data/logs` When the logs folder is not present, `tpm2d` segfaults and crashes a freshly installed OS.  This only happens when a TPM2 is enabled and present.  Moving the `mkdir` of `/data/logs` up ahead of where the `tpm2d -n` is launched to allow for a successful boot.
=> Update cml-boot-script.stub to allow TPM2 enabled devices to configure

recipes-initscripts/cml-boot/files/cml-boot-script.stub, recipes-poky/base-files/base-files/fstab
Currently, booting is instable, thus we switch back to fstab based mounting with 'mount -a' in the cml-init script.
This partially reverts commit 49f7e0cf4c326dccd13ea378ecb657ade35ef3bd ("initscripts/poky: Restructure fs mounting").
=> initscripts/poky: switch back to fstab mounting with 'mount -a'

recipes-initscripts/cml-boot/files/cml-boot-script.stub
In case of /data is already mounted by debugging feature including extdata and containers mountpoints, bind mount or overlay mounts are already set up. Thus, the bind mount from /mnt/userdata to /data in cm-boot-script.stub would over mount this again. Fix this by just checking if /data is already mounted with 'mountpoint'.
Fixes: ee0cbe220b4a ("initscripts/poky: switch back to fstab mounting with 'mount -a'")
=> initscripts/poky: do not over mount '/data' if already mounted

classes/p11-signing.bbclass, classes/trustmegeneric.bbclass, images/trustx-cml-firmware.bb, images/trustx-cml-initramfs.bb, recipes-kernel/linux/linux-gyroidos.inc
Checking if a Yocto variable starts with "pkcs11:" in POSIX compliant shell turns out to be complicated. Implement a helper function in p11-signing.bbclass.
=> treewide: Implement PKCS#11 URI checking using helper function

recipes-tss/openssl-tpm2-engine/openssl-tpm2-engine/Fix-32-bit-errors_4.3.0.patch, recipes-tss/openssl-tpm2-engine/openssl-tpm2-engine_4.3.0.bb
Recent update to 4.3.0 did not compile on 32bit arch. Thus, added backport of upstream commit 508060a88b6e ("Fix 32 bit errors").
Fixes: d8b99868876a ("recipes-tss/openssl-tpm2-engine: updated to version 4.3.0")
=> recipes-tss/openssl-tpm2-engine: added 32bit compat patch

recipes-trustx/cmld/cml-common.inc
To make remotes configurable we moved the host part of the uri to a separate variable called CML_HOST.
=> recipes-trustx/cmld: make host configurable

conf/multiconfig/container_qemuarm.inc, conf/multiconfig/container_qemuarm64.inc
In container_qemuarm*.inc linux-dummy were set as preferred kernel provider for the gyroidos-core distro. However this was renamed to core-ref. Thus, also set linux-dummy for the core-ref distro and not gyroidos-core anymore.
Fixes: b5299ba2f996 ("conf: renamed distros gyroidos-{cml,core} to cml-base, core-ref")
=> conf/multiconfig: set linux-dummy for core-ref for qemuarm

recipes-gyroidos/userdata/pki-native.bb
To set the appropriate key size for (e.g. RPi 4, 2048 bit only) secure boot mechanisms, set the default key size to 4096 bit but allow setting overriding the key size in a device config file.
test with: https://github.com/gyroidos/gyroidos_build/pull/121
=> recipes-trustx/userdata/pki-native: Allow key size override

recipes-poky/base-files/base-files/fstab
This PR removes the entry 'gyroidos' from the fstab as the label is only used during initial formatting and debugging builds on platforms without a TPM. There, the data partiion is explicitly mountet by LABEL in
=> recipes-poky/base-files: Remove entry from fstab

images/gyroidos-cml-firmware.bb
In a case where the certificate is provided by file by the private key is located on a PKCS#11 token, we erroneouly append the file ending, thus resulting in e.g. 'ssig_subca.der.der'. Fix by only appending the '.der' ending if the cerificate comes from PKCS#11.
=> images/gyroidos-cml-firmware: Fix path to certificate

recipes-initscripts/cml-boot/files/cml-boot-script.stub
Booting GyroidOS in VirtualBox with TPM2.0 enabled led to the network interfaces to disappear after the 2º boot and having the UI behaving abnormally in the VirtualBox window. Collapsing both 2 second sleeps into one 4 second sleep before 'udevadm trigger --type=devices' and after the first 'udevadm settle' fixed the issue.
=> recipes-initscripts: cml-boot-script: Change scan_devices sleep timer

conf/distro/cml-base.conf, images/gyroidos-cml-initramfs.bb
Removed python dependency in scarthgap builds and protobuf debug symbols
=> Reduce size of Initramfs in debug builds
